import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { CategoriesProvider } from "@/components/context/category";
import AuthProvider from "./authProvider";
import { Toaster } from "react-hot-toast";
import TopLoader from "@/components/topLoader";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Navbar />
          <TopLoader />
          <CategoriesProvider>
            <Toaster />
            {children}
          </CategoriesProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
